### ISSUE TITLE
Skipulag síðu

### ISSUE THREAD

**Issue by bjarkih1977** [piratar/new.piratar.is#4]
Gott væri að hafa eitthvað annað en viðburði mest áberandi þegar síðan er opnuð.  Betra væri að hafa þá í dálk t.d. hægra meginn.  Þetta er vegna þess að þegar maður er úti á landi og er bara að leita sér að upplýsingum um pírata þá er vont að fá því skellt í andlitið á sér að það sé lögð mest áhersla á viðburði sem eru ekki einu sinni í boði fyrir stærstan hluta landsins.
![piratar](https://user-images.githubusercontent.com/26550596/60735429-cf888780-9f42-11e9-885e-2df683bbfe4a.png)

**Comment by viktorsmari** [comment]
Viðburðirnir verða ekki mest áberandi þegar síðan er opnuð.
Skoðaðir þú ekki hönnunarskjölin?

Þau eru hér:
https://github.com/piratar/new.piratar.is/issues/1
